apiVersion: pipecd.dev/v1beta1
kind: CloudRunApp
spec:
  name: canary-app
  pipeline:
    stages:
      - name: CLOUDRUN_PROMOTE
        with:
          percent: 20
  description: |
    This app demonstrates how to deploy a Cloud Run application with Canary.
